# Generated by Django 4.1.2 on 2022-11-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(null=True, upload_to="images'"),
        ),
    ]
